name: Tests
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: npm test
